services:
  - type: web
    name: phi-finance-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python playground.py
    envVars:
      - key: PHI_API_KEY
        sync: false
